# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require "shellwords"

default_platform(:mac)

bundle_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
developer_team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

def verify_developer_id_app!(app_path, expected_team_id)
  app = File.expand_path(app_path)
  sh("codesign", "--verify", "--deep", "--strict", "--verbose=4", app)

  checks = {
    "PlayCover.app" => app,
    "Sparkle.framework" => File.join(app, "Contents/Frameworks/Sparkle.framework"),
    "PlayTools.framework" => File.join(app, "Contents/Frameworks/PlayTools.framework"),
  }

  checks.each do |name, path|
    UI.user_error!("#{name} is missing at #{path}") unless File.exist?(path)

    details = sh("codesign --display --verbose=4 #{path.shellescape} 2>&1", log: false)
    UI.user_error!("#{name} was signed ad-hoc") if details.include?("Signature=adhoc")

    team_match = details.match(/^TeamIdentifier=(.+)$/)
    team_id = team_match && team_match[1].strip
    next if team_id == expected_team_id

    UI.user_error!("#{name} TeamIdentifier is #{team_id || "missing"}, expected #{expected_team_id}")
  end
end

platform :mac do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end


lane :release do
  setup_ci if ENV['CI']
  match(type: "developer_id", readonly: true)
  Dir.chdir("..") do
    sh("carthage", "update", "--use-xcframeworks")
  end
  build_mac_app(
    configuration: "Release",
    scheme: "PlayCover",
    output_directory: "output",
    output_name: "PlayCover",
    export_method: "developer-id",
    destination: "generic/platform=macOS",
    skip_package_pkg: true,
    xcargs: "FASTLANE=1",
    )
  verify_developer_id_app!("output/PlayCover.app", developer_team_id)
end

lane :nightly do
  setup_ci if ENV['CI']
  match(type: "developer_id", readonly: true)
  Dir.chdir("..") do
    sh("carthage", "update", "--use-xcframeworks")
  end
  carthage(use_xcframeworks: true)
  build_mac_app(
    configuration: "Nightly",
    scheme: "PlayCover",
    output_directory: "output",
    output_name: "PlayCover",
    export_method: "developer-id",
    destination: "generic/platform=macOS",
    skip_package_pkg: true,
    xcargs: "FASTLANE=1",
    )
  verify_developer_id_app!("output/PlayCover.app", developer_team_id)
end

lane :notarize_app do
  notarize(
    package: "output/PlayCover.app",
    api_key_path: "apikey.json",
    bundle_id: bundle_id,
  )
end

lane :notarize_dmg do |options|
  notarize(
    use_notarytool: true,
    package: options[:package],
    api_key_path: "apikey.json",
    bundle_id: bundle_id,
    print_log: true,
    # verbose: true,
  )
end

lane :rename_dmg do
  sh(
    "cd .. && find output -name '*.dmg' -exec mv {} output/PlayCover.dmg \\;",
  )
end
